### PR TITLE
target: Speed-up read_tree_values()

### PR DESCRIPTION
**Pull request by qperret**
Since target.read_tree_values() has been modified to use tar as a way to
fetch the content of files from the target, it is more robust, but also
much slower. Since that level of robustness is in practice required only
for very specific use-cased, re-introduce the old way of doing read_tree
using find and grep.

read_tree_values() gains a new parameter to specify how files should be
read from the target, with or without tar. It defaults to the old way
of doing things.

Signed-off-by: Quentin Perret <quentin.perret@arm.com>

### CODE REVIEW

**Comment by douglas-raillard-arm** [comment]
Shouldn't the code that works all the time be the default, and have an option to speed it up when it is known to not break ? That would avoid ending up with user code that seems to work on a machine and then starts failing on another one just because an "annoying" file shows up there in sysfs.

If tar=False becomes the default, the `hwmon` module should probably make use of `tar=True` since it is known to break on some hosts with the previous `read_tree_values` implementation.

**Comment by qperret** [comment]
It feels to me that the significant majority of cases work just fine with the old grep-based implementation. So it probably makes sense to have the default that suits most users.

I'll add a commit to fix hwmon ;)

**Comment by douglas-raillard-arm** [comment]
I don't know about how WA uses devlib, but you could argue that the significant majority of cases in LISA work just fine with the functionally correct tar-based implementation. Next user tripping on that (maybe through a devlib module, maybe via 3rd party code) is likely to unnecessarily loose time on an issue that has been identified, debugged and solved in backward compatible way, but was just not enabled by default.

**Comment by qperret** [comment]
Yeah but I also care about keeping Lisa fast, and that tar-based implementation made it worse. And the option is documented so users should read the doc IMO :).
I added the fix for hwmon.

**Comment by setrofim** [comment]
It can be argued that it is preferable to have an overt failure than an inexplicable slow down. In the former case, it is at least clear than there is a problem, in the latter the user might not even be aware that the issue can be rectified.

In either case the docs should be updated to describe this issue and why ``tar`` flag even exists.

**Comment by qperret** [comment]
Ah, right, the docstring isn't enough ... I'll go write something in doc/

**Comment by douglas-raillard-arm** [comment]
After a bit of investigations, not handling MAXDEPTH in the shell script (which forces to have a loop+find) and just copying everything with `cp -R` restores normal speed. It is possible to handle that on the Python side if necessary. That won't work if the tree contains really big files deep in the hierarchy, but for /sys/devices/system/cpu it does the job well and simplifies `shutils.in`.

**Comment by qperret** [comment]
I added a paragraph to the doc of read_tree_values(). Let me know if that works for you.

**Pull request merged**
