### PR TITLE
target: support threads in ps

### PR DESCRIPTION
**Pull request by stephenkyle-ARM**
By passing 'threads=True' to target.ps(), a list of PsThreadEntrys will be
returned for all threads in the target, not just processes. These entries
include an extra value 'tid': the thread ID of this thread. The 'pid' value
represents the pid of the process the thread belongs to.

### CODE REVIEW

**Comment by stephenkyle-ARM** [comment]
I've tested this on both Linux (sshing into a workstation) and Android device. This provides some functionality for a future PR: the perf instrument attaching to threads of processes based on search terms.

**Comment by setrofim** [comment]
It's not a good idea to have the result change based on the argument. Why not just modify the existing `PsEntry` to have the `tid`?

**Comment by stephenkyle-ARM** [comment]
Fair, but what should the value of `tid` be in that case? The same as `pid`? `None`?

**Comment by setrofim** [comment]
It should be the `tid`  for the main thread of the process; i.e. the same as  `pid`.

**Comment by stephenkyle-ARM** [comment]
Updated, PTAL.

**Pull request merged**
