### PR TITLE
Fix race in LogcatMonitor

### PR DESCRIPTION
**Pull request by bjackman**

### CODE REVIEW

**Comment by bjackman** [comment]
CC @valschneider

**Comment by bjackman** [comment]
nope! still a race, updating shortly

**Comment by bjackman** [comment]
Fixed. I hope the commit message makes sense..

**Comment by bjackman** [comment]
Fixed. I hope the commit message makes sense..

**Comment by setrofim** [comment]
What happens if `stop()` is called before `start() `? It *is* illegal, but we want a better failure mode than "wait forever". 

Proposed solution: Make sure `_stopped` is set inside `__init__`, unset it inside `start`,  immediately return from `stop` if `_stopped` is set.

**Comment by valschneider** [comment]
@setrofim Couldn't we just use this:

```
if not self.is_active()
    return
```

The way I see it, `self.is_active()` answers the question "have I called start?"

**Comment by bjackman** [comment]
Updated with the check for `is_alive`

**Pull request merged**
